// flow-typed signature: 344711d56ea02c8d4cfec6e6c0bdf6d7
// flow-typed version: <<STUB>>/binance_v^1.1.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'binance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'binance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'binance/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'binance/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'binance/lib/beautifier' {
  declare module.exports: any;
}

declare module 'binance/lib/binance' {
  declare module.exports: any;
}

declare module 'binance/lib/rest' {
  declare module.exports: any;
}

declare module 'binance/lib/ws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'binance/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'binance/coverage/lcov-report/prettify'>;
}
declare module 'binance/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'binance/coverage/lcov-report/sorter'>;
}
declare module 'binance/lib/beautifier.js' {
  declare module.exports: $Exports<'binance/lib/beautifier'>;
}
declare module 'binance/lib/binance.js' {
  declare module.exports: $Exports<'binance/lib/binance'>;
}
declare module 'binance/lib/rest.js' {
  declare module.exports: $Exports<'binance/lib/rest'>;
}
declare module 'binance/lib/ws.js' {
  declare module.exports: $Exports<'binance/lib/ws'>;
}
